# Generated by Django 6.0.6 on 2026-06-13 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_trustscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustscore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trustscore',
            name='recommendation',
            field=models.CharField(max_length=50),
        ),
    ]
